### ISSUE TITLE
Generate inventory doesn't allow to create inventory file for local deployment

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/cloud-native-infra#5]
Generate inventory template doesn't allow to create inventory file for local deployment 
and instructions doesn't mention to generate the inventory file 

https://github.com/snowdrop/cloud-native-infra/blob/master/ansible/README-VM.md#ansible-started-locally

**Comment by geoand** [comment]
This is just a documentation issue if I understand correctly.
There is a use_local flag that the user needs to set to true when calling
the generate_inventory playbook.
But I must have forgot to documenting it

**Comment by geoand** [comment]
I updated the `README-VM` documentation to include 

`ansible-playbook playbook/generate_inventory.yml -e ip_address=192.168.99.50`

The documentation on how to install Openshift while running the Ansible playbook from within the VM was already correct, since the following command is mentioned:

`ssh root@192.168.99.50 "cd install && ansible-playbook playbook/generate_inventory.yml -e ip_address=192.168.99.50 -e use_local=true"`

**Comment by cmoulliard** [comment]
Do we need 2 separate README fil,  I don't think so  ? @geoand

**Comment by geoand** [comment]
I personally prefer having two different files, it makes each use case clear.
However I am not opposed to merging them if you want to try it and see what it looks like :)
